### ISSUE TITLE
java.io.FileNotFoundException in BuildNow

### ISSUE THREAD

**Issue by stenpiren** [hakdogan/jenkins-pipeline#1]
Hi,

After following the steps upto "Build Now" I get an error:

`
java.io.FileNotFoundException
	at jenkins.plugins.git.GitSCMFile$3.invoke(GitSCMFile.java:167)
	at jenkins.plugins.git.GitSCMFile$3.invoke(GitSCMFile.java:159)
	at jenkins.plugins.git.GitSCMFileSystem$3.invoke(GitSCMFileSystem.java:193)
	at org.jenkinsci.plugins.gitclient.AbstractGitAPIImpl.withRepository(AbstractGitAPIImpl.java:29)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.withRepository(CliGitAPIImpl.java:72)
	at jenkins.plugins.git.GitSCMFileSystem.invoke(GitSCMFileSystem.java:189)
	at jenkins.plugins.git.GitSCMFile.content(GitSCMFile.java:159)
	at jenkins.scm.api.SCMFile.contentAsString(SCMFile.java:338)
	at org.jenkinsci.plugins.workflow.cps.CpsScmFlowDefinition.create(CpsScmFlowDefinition.java:109)
	at org.jenkinsci.plugins.workflow.cps.CpsScmFlowDefinition.create(CpsScmFlowDefinition.java:67)
	at org.jenkinsci.plugins.workflow.job.WorkflowRun.run(WorkflowRun.java:263)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)
Finished: FAILURE
`

What could be the cause? Do we have to make changes in the provided JenkinsFile?

**Comment by hakdogan** [comment]
Hi @stenpiren 

The jenkins file should be available in main directory path. Did you change the directory?

**Comment by stenpiren** [comment]
Hi @hakdogan . No I didnt change anything. Simply built the images and followed the steps to configure. I added my dockerhub login and password, yet I get an error.

**Comment by hakdogan** [comment]
I understand. 

I do not know any other reason for this exception.

Were the steps to install the plugin successfully completed?

**Comment by hakdogan** [comment]
Is the script path define like in the picture?
![012](https://user-images.githubusercontent.com/657846/43223447-c66def9c-905b-11e8-939f-1b58ef5975a8.png)

**Comment by stenpiren** [comment]
hi @hakdogan . It works. I thought that in the repository URL I was suppose to use mine while in reality was yours. Then later I changed to your repository URL and it worked. I have some off questions to make. Would send you by e-mail. Thanks a lot :)

**Comment by adi07das** [comment]
@stenpiren , uncheck the Lightweight checkout

**Comment by VarunVashishtha** [comment]
it worked for me , thankyou so much @stenpiren

**Comment by thanh-nguyen-van** [comment]
thanks @adi07das

**Comment by hitesh211** [comment]
Somebody please tell me how i resolve this error :-

Started by user unknown or anonymous
ERROR: Unable to find Jenkinsfile from git git@github.com:hitesh211/node-todo.git
Finished: FAILURE
